// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ighdgcuzmtxmxocyvjch.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnaGRnY3V6bXR4bXhvY3l2amNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDM5OTIsImV4cCI6MjA2NDI3OTk5Mn0.CQBxghBUpxjB4Slg2BLf47sj5a99yAMv_9AvCIIn86Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);